#define CONFIG_NAMESPACE "config"
#define CONFIG_WIFI_SSID_KEY "wifi_ssid"
#define CONFIG_WIFI_PASS_KEY "wifi_pass"
#define CONFIG_ESP_MAXIMUM_RETRY 10

#define SOFT_AP_SSID "DonWatio"
#define SOFT_AP_PASS "password"
#define SOFT_AP_MAX_CONNECTION 4

#define SOFT_AP_IP_ADDRESS_1 192
#define SOFT_AP_IP_ADDRESS_2 168
#define SOFT_AP_IP_ADDRESS_3 7
#define SOFT_AP_IP_ADDRESS_4 1

#define SOFT_AP_GW_ADDRESS_1 192
#define SOFT_AP_GW_ADDRESS_2 168
#define SOFT_AP_GW_ADDRESS_3 7
#define SOFT_AP_GW_ADDRESS_4 5

#define SOFT_AP_NM_ADDRESS_1 255
#define SOFT_AP_NM_ADDRESS_2 255
#define SOFT_AP_NM_ADDRESS_3 255
#define SOFT_AP_NM_ADDRESS_4 0
